DEFAULT_ENGINE_ELO = 2000
MIN_RELIABLE_CONFIDENCE = 0.95
MIN_RELIABLE_CONFIDENCE_WITH_STRONG_STABILITY = 0.93
MIN_RELIABLE_QUALITY = 10
MIN_RELIABLE_STABILITY = 2
MIN_RELIABLE_STRONG_STABILITY = 6

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
EXCLUDED_IMAGE_DIRS = {"venv", ".git", "__pycache__"}
IGNORED_IMAGE_PREFIXES = ("cropped", "warped")

DEBUG_IMAGE_ENV_VAR = "CHESS_SAVE_DEBUG_IMAGES"
